"""add notification fields to assignment

Revision ID: 5eb5ce53373d
Revises: da9372eebecb
Create Date: 2026-06-05 20:46:49.974849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb5ce53373d'
down_revision = 'da9372eebecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notification_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('notification_date')
        batch_op.drop_column('notification_sent')

    # ### end Alembic commands ###
