"""initial migration

Revision ID: b53025d8566b
Revises: 
Create Date: 2026-06-01 12:11:20.013029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b53025d8566b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scc_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parish_rank', sa.Integer(), nullable=True),
    sa.Column('representative_contact', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('masses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('animating_scc_id', sa.Integer(), nullable=True),
    sa.Column('feast_day_details', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['animating_scc_id'], ['scc_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proclaimers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scc_id', sa.Integer(), nullable=True),
    sa.Column('is_certified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('last_assigned_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scc_id'], ['scc_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proclaimers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proclaimers_last_assigned_date'), ['last_assigned_date'], unique=False)

    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mass_id', sa.Integer(), nullable=False),
    sa.Column('proclaimer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_fallback', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mass_id'], ['masses.id'], ),
    sa.ForeignKeyConstraint(['proclaimer_id'], ['proclaimers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignments')
    with op.batch_alter_table('proclaimers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proclaimers_last_assigned_date'))

    op.drop_table('proclaimers')
    op.drop_table('masses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('scc_groups')
    # ### end Alembic commands ###
