"""add phone_number to proclaimer

Revision ID: da9372eebecb
Revises: b53025d8566b
Create Date: 2026-06-01 15:18:58.363936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da9372eebecb'
down_revision = 'b53025d8566b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proclaimers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proclaimers', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
